export const ERROR_CODES = {
  UNDERPAYMENT: 'UNDERPAYMENT', OVERPAYMENT: 'OVERPAYMENT', EXPIRED: 'TRANSACTION_EXPIRED',
  PAYMENT_NOT_DETECTED: 'PAYMENT_NOT_DETECTED', EXCHANGE_RATE: 'EXCHANGE_RATE_UNAVAILABLE',
  ZCASH_NETWORK: 'ZCASH_NETWORK_FAILURE', INVALID_RECIPIENT: 'INVALID_RECIPIENT',
  PAYOUT_FAILED: 'PAYOUT_FAILED', DUPLICATE: 'DUPLICATE_PROCESSING', CANCELLED: 'CANCELLED'
}
export function appError(code, message, retryable = false, details) { return { code, message, retryable, details, at: new Date().toISOString() } }
