export const ERROR_CODES = {
  UNDERPAYMENT: 'UNDERPAYMENT',
  OVERPAYMENT: 'OVERPAYMENT',
  TRANSACTION_EXPIRED: 'TRANSACTION_EXPIRED',
  PAYMENT_NOT_DETECTED: 'PAYMENT_NOT_DETECTED',
  EXCHANGE_RATE_UNAVAILABLE: 'EXCHANGE_RATE_UNAVAILABLE',
  ZCASH_NETWORK_UNAVAILABLE: 'ZCASH_NETWORK_UNAVAILABLE',
  INVALID_RECIPIENT: 'INVALID_RECIPIENT',
  PAYOUT_FAILED: 'PAYOUT_FAILED',
  DUPLICATE_PROCESSING: 'DUPLICATE_PROCESSING',
  CANCELLED: 'CANCELLED',
} as const

export type TransactionErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES]
export type TransactionError = { code: TransactionErrorCode; message: string; retryable: boolean; at: string; details?: unknown }
