export const STATUSES = [
  'CREATED','AWAITING_ZEC','ZEC_DETECTED','CONFIRMING','ZEC_CONFIRMED','PAYOUT_PROCESSING','FIAT_SENT','COMPLETED',
  'EXPIRED','UNDERPAID','OVERPAID','PAYOUT_FAILED','CANCELLED'
]

export const TRANSITIONS = {
  CREATED: ['AWAITING_ZEC','CANCELLED'],
  AWAITING_ZEC: ['ZEC_DETECTED','UNDERPAID','OVERPAID','EXPIRED','CANCELLED'],
  ZEC_DETECTED: ['CONFIRMING','UNDERPAID','OVERPAID','EXPIRED','CANCELLED'],
  CONFIRMING: ['ZEC_CONFIRMED','UNDERPAID','OVERPAID','EXPIRED','CANCELLED'],
  ZEC_CONFIRMED: ['PAYOUT_PROCESSING'],
  PAYOUT_PROCESSING: ['FIAT_SENT','PAYOUT_FAILED'],
  FIAT_SENT: ['COMPLETED','PAYOUT_FAILED'],
  COMPLETED: [], EXPIRED: [], UNDERPAID: ['ZEC_DETECTED','CONFIRMING','ZEC_CONFIRMED'], OVERPAID: [], PAYOUT_FAILED: ['PAYOUT_PROCESSING'], CANCELLED: []
}

export function canTransition(from, to) { return from === to || (TRANSITIONS[from] || []).includes(to) }
export function assertTransition(from, to) { if (!canTransition(from, to)) throw new Error(`Invalid transaction transition: ${from} -> ${to}`) }
export function isTerminal(status) { return ['COMPLETED','EXPIRED','OVERPAID','CANCELLED'].includes(status) }
