import http from 'node:http'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { JsonStore } from './src/store.mjs'
import { createNodeManager } from './src/node-manager.mjs'
import { monitorOrder } from './src/payment-monitor.mjs'
import { createPayoutProvider } from './src/payout-service.mjs'
import { appError, ERROR_CODES } from './src/error-codes.mjs'
import { assertTransition } from './src/status-engine.mjs'

const root=path.dirname(fileURLToPath(import.meta.url)); const PORT=Number(process.env.PORT||8787); const DB=process.env.PRIVATE_BILL_DB||path.join(root,'data/private-bill.json'); const CONFIRMATIONS=Number(process.env.ZCASH_REQUIRED_CONFIRMATIONS||3); const ACTIVE_NETWORK=(process.env.PRIVATE_BILL_NETWORK||'testnet').toLowerCase(); const store=new JsonStore(DB); await store.init(); const payoutLocks=new Set(); const payoutProvider=createPayoutProvider()
function json(res,status,body){res.writeHead(status,{'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*'});res.end(JSON.stringify(body))}
function body(req){return new Promise((resolve,reject)=>{let raw='';req.on('data',c=>raw+=c);req.on('end',()=>{try{resolve(raw?JSON.parse(raw):{})}catch(e){reject(e)}});req.on('error',reject)})}
function validateOrder(i){for(const k of ['id','fiatCurrency','fiatAmount','requiredZec','recipient','depositAddress'])if(!i[k])throw new Error(`Missing order field: ${k}`);if(!['NGN','GHS'].includes(i.fiatCurrency))throw new Error('Unsupported fiat currency');if(Number(i.fiatAmount)<=0||Number(i.requiredZec)<=0)throw new Error('Amounts must be positive');if(!i.recipient.accountNumber||!i.recipient.accountName||!i.recipient.providerName)throw new Error('Invalid recipient information');if(i.recipient.currency!==i.fiatCurrency)throw new Error('Recipient currency does not match order currency')}
async function routes(req,res){const url=new URL(req.url,`http://${req.headers.host}`);if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type'});return res.end()}
try{
 if(req.method==='GET'&&url.pathname==='/api/config'){const m=createNodeManager();return json(res,200,{network:m.network,nodePreference:m.preference,requiredConfirmations:CONFIRMATIONS,payoutProvider:payoutProvider.name})}
 if(req.method==='GET'&&url.pathname==='/api/health'){const m=createNodeManager();try{const n=await m.select();return json(res,200,{ok:true,network:m.network,selectedNode:n.name,payoutProvider:payoutProvider.name})}catch(e){return json(res,503,{ok:false,network:m.network,error:e.message,details:e.details})}}
 if(req.method==='POST'&&url.pathname==='/api/orders'){const input=await body(req);try{validateOrder(input)}catch(e){return json(res,422,{ok:false,error:e.message,errorCode:ERROR_CODES.INVALID_RECIPIENT})}const order={...input,network:input.network||ACTIVE_NETWORK,status:'CREATED',createdAt:input.createdAt||new Date().toISOString(),expiresAt:input.expiresAt||new Date(Date.now()+30*60*1000).toISOString()};await store.createOrder(order);await store.transitionOrder(order.id,'AWAITING_ZEC','Order accepted and awaiting ZEC');return json(res,201,store.getOrder(order.id))}
 const statusMatch=url.pathname.match(/^\/api\/orders\/([^/]+)\/status$/);if(req.method==='GET'&&statusMatch){const order=store.getOrder(decodeURIComponent(statusMatch[1]));if(!order)return json(res,404,{error:'Order not found'});return json(res,200,{id:order.id,status:order.status,statusHistory:order.statusHistory||[],statusTimestamps:order.statusTimestamps||{},lastError:order.lastError||null,payment:order.payment||null,payout:order.payout||null,fiatCurrency:order.fiatCurrency,fiatAmount:order.fiatAmount,requiredZec:order.requiredZec,recipient:order.recipient})}
 const monitorMatch=url.pathname.match(/^\/api\/payment-monitor\/([^/]+)$/);if(req.method==='GET'&&monitorMatch){const order=store.getOrder(decodeURIComponent(monitorMatch[1]));if(!order)return json(res,404,{error:'Order not found'});try{const m=createNodeManager();if(order.network&&order.network!==m.network)return json(res,409,{error:`Order network ${order.network} does not match active backend network ${m.network}`});return json(res,200,await monitorOrder(store,m,order,CONFIRMATIONS))}catch(e){const err=appError(ERROR_CODES.ZCASH_NETWORK,e.message,true,e.details);await store.recordError(order.id,err);return json(res,503,{state:order.status,payment:null,checkedAt:new Date().toISOString(),source:'unavailable',network:ACTIVE_NETWORK,error:err.message,errorCode:err.code,retryable:true})}}
 const payoutMatch=url.pathname.match(/^\/api\/orders\/([^/]+)\/payout$/);if(req.method==='POST'&&payoutMatch){const id=decodeURIComponent(payoutMatch[1]);let order=store.getOrder(id);if(!order)return json(res,404,{error:'Order not found'});if(payoutLocks.has(id)||order.status==='PAYOUT_PROCESSING'){const e=appError(ERROR_CODES.DUPLICATE,'A payout attempt is already being processed.',true);await store.recordError(id,e);return json(res,409,{error:e.message,errorCode:e.code,retryable:true})}if(order.status!=='ZEC_CONFIRMED'&&order.status!=='PAYOUT_FAILED')return json(res,409,{error:`Payout cannot start from ${order.status}`});payoutLocks.add(id);try{await store.clearError(id);order=await store.transitionOrder(id,'PAYOUT_PROCESSING','Payout initiated');const attempt={id:`ATT-${Date.now().toString(36).toUpperCase()}`,startedAt:new Date().toISOString(),provider:payoutProvider.name};order=await store.updateOrder(id,{payoutAttempts:[...(order.payoutAttempts||[]),attempt]});const result=await payoutProvider.payout({order});order=await store.updateOrder(id,{payout:{...result,attemptId:attempt.id},lastError:null});order=await store.transitionOrder(id,'FIAT_SENT','Payout provider confirmed fiat delivery');order=await store.transitionOrder(id,'COMPLETED','Transaction completed');return json(res,200,{ok:true,order})}catch(e){const err=appError(ERROR_CODES.PAYOUT_FAILED,e.message,true,{providerCode:e.providerCode});await store.recordError(id,err);try{order=await store.transitionOrder(id,'PAYOUT_FAILED','Payout provider failed')}catch{}return json(res,502,{ok:false,order:store.getOrder(id),error:err.message,errorCode:err.code,retryable:true})}finally{payoutLocks.delete(id)}}
 const cancelMatch=url.pathname.match(/^\/api\/orders\/([^/]+)\/cancel$/);if(req.method==='POST'&&cancelMatch){const id=decodeURIComponent(cancelMatch[1]);const order=store.getOrder(id);if(!order)return json(res,404,{error:'Order not found'});if(!['AWAITING_ZEC','ZEC_DETECTED','CONFIRMING','UNDERPAID'].includes(order.status))return json(res,409,{error:`Cannot cancel ${order.status}`});const updated=await store.transitionOrder(id,'CANCELLED','Cancelled by user');await store.recordError(id,appError(ERROR_CODES.CANCELLED,'Transaction cancelled. No payout can be initiated.',false));return json(res,200,{ok:true,order:updated})}
 if(req.method==='GET'&&url.pathname==='/api/orders')return json(res,200,store.listOrders())
 return json(res,404,{error:'Not found'})
}catch(e){return json(res,400,{error:e.message})}}
http.createServer(routes).listen(PORT,()=>console.log(`Private Bill Quest 12 backend listening on http://127.0.0.1:${PORT}`))
